dbMemo "SQL" ="SELECT tblPress.ID, tblPARTNUM.partNum, refREV.rev\015\012FROM (tblPress INNER J"
    "OIN tblPARTNUM ON tblPress.partNum = tblPARTNUM.ID) INNER JOIN refREV ON tblPres"
    "s.Rev = refREV.ID\015\012WHERE (((tblPress.partNum)=861) AND ((tblPress.rev)=28)"
    " AND ((tblPress.obsolete)=False) AND ((tblPress.[R&D])=False));\015\012"
dbMemo "Connect" =""
dbBoolean "ReturnsRecords" ="-1"
dbInteger "ODBCTimeout" ="60"
dbByte "RecordsetType" ="2"
dbBoolean "OrderByOn" ="0"
dbByte "Orientation" ="0"
dbByte "DefaultView" ="2"
dbBoolean "FilterOnLoad" ="0"
dbBoolean "OrderByOnLoad" ="-1"
dbBoolean "TotalsRow" ="0"
