SELECT TOP 25 tblMAINTENANCE_DAILY_CR.timeDate, tblMAINTENANCE_DAILY_CR.timeHour, tblMAINTENANCE_DAILY_CR.temperature, tblMAINTENANCE_DAILY_CR.tankA, tblMAINTENANCE_DAILY_CR.tankB, tblTECHNAME.firstName
FROM tblMAINTENANCE_DAILY_CR LEFT JOIN tblTECHNAME ON tblMAINTENANCE_DAILY_CR.techName = tblTECHNAME.ID
WHERE (((tblMAINTENANCE_DAILY_CR.temperature)<>0))
ORDER BY tblMAINTENANCE_DAILY_CR.timeDate DESC , tblMAINTENANCE_DAILY_CR.timeHour DESC;
