SELECT tblMAINTENANCE_DAILY_CR.timeDate, tblMAINTENANCE_DAILY_CR.timeHour, tblMAINTENANCE_DAILY_CR.temperature, tblMAINTENANCE_DAILY_CR.tankA, tblMAINTENANCE_DAILY_CR.tankB, tblTECHNAME.firstName, tblTECHNAME.lastName
FROM tblTECHNAME RIGHT JOIN tblMAINTENANCE_DAILY_CR ON tblTECHNAME.ID = tblMAINTENANCE_DAILY_CR.techName
WHERE (((tblMAINTENANCE_DAILY_CR.timeDate)>=#1/2/2020#) AND ((IsNull([tankB]))=False))
ORDER BY tblMAINTENANCE_DAILY_CR.timeDate, tblMAINTENANCE_DAILY_CR.timeHour;
