dbMemo "SQL" ="SELECT subQry.uniqID, subQry.autoID, subQry.tbl, subQry.partNumber, subQry.partU"
    "seage, tblPART_TYPES.partType, tblPART_STORAGE.locName, subQry.linkedID, subQry."
    "notes, subQry.location, refREV.rev, tblSUBCATEGORY.category, subQry.subcategory\015"
    "\012FROM ((((SELECT ('C' & autoID) as uniqID, autoID, rev, 'tblPART_156' as tbl,"
    " partNumber, partUseage, location, linkedID, notes, subcategory from tblPART_156"
    "\015\012UNION ALL\015\012SELECT ('A' & autoID) as uniqID, autoID, rev, 'tblPART_"
    "01' as tbl, partNumber, partUseage, location, linkedID, notes, subcategory from "
    "tblPART_01 \015\012UNION ALL \015\012SELECT ('B'&autoID) as uniqID, autoID, rev,"
    " 'tblPART_07' as tbl, partNumber, partUseage, location, linkedID, notes, subcate"
    "gory from tblPART_07)  AS subQry LEFT JOIN tblPART_TYPES ON subQry.partUseage = "
    "tblPART_TYPES.ID) LEFT JOIN tblPART_STORAGE ON subQry.location = tblPART_STORAGE"
    ".ID) LEFT JOIN refREV ON subQry.rev = refREV.ID) LEFT JOIN tblSUBCATEGORY ON sub"
    "Qry.subcategory = tblSUBCATEGORY.ID;\015\012"
dbMemo "Connect" =""
dbBoolean "ReturnsRecords" ="-1"
dbInteger "ODBCTimeout" ="60"
dbBoolean "OrderByOn" ="0"
dbByte "Orientation" ="0"
dbByte "DefaultView" ="2"
dbBoolean "FilterOnLoad" ="0"
dbBoolean "OrderByOnLoad" ="-1"
dbByte "RecordsetType" ="0"
dbBoolean "TotalsRow" ="0"
