dbMemo "SQL" ="SELECT tblPART_07.partNumber, refREV.rev, tblPART_07.obsolete, tblPART_07.[r&d],"
    " tblPART_TYPES.partType, tblPART_07.notes, tblSUBCATEGORY.category\015\012FROM ("
    "(tblPART_07 LEFT JOIN refREV ON tblPART_07.Rev = refREV.ID) LEFT JOIN tblPART_TY"
    "PES ON tblPART_07.partuseage = tblPART_TYPES.ID) LEFT JOIN tblSUBCATEGORY ON tbl"
    "PART_07.subcategory = tblSUBCATEGORY.ID\015\012ORDER BY tblPART_07.partNumber, r"
    "efREV.rev;\015\012"
dbMemo "Connect" =""
dbBoolean "ReturnsRecords" ="-1"
dbInteger "ODBCTimeout" ="60"
dbByte "RecordsetType" ="2"
dbBoolean "OrderByOn" ="0"
dbByte "Orientation" ="0"
dbByte "DefaultView" ="2"
dbBoolean "FilterOnLoad" ="0"
dbBoolean "OrderByOnLoad" ="-1"
dbBoolean "TotalsRow" ="0"
dbMemo "Filter" ="([qryPART_07].[category]=\"Manifold Flange\")"
dbText "DatasheetFontName" ="Calibri"
dbInteger "DatasheetFontHeight" ="14"
dbInteger "DatasheetFontWeight" ="400"
dbBoolean "DatasheetFontItalic" ="0"
dbBoolean "DatasheetFontUnderline" ="0"
dbByte "TabularCharSet" ="0"
dbByte "TabularFamily" ="34"
dbLong "DatasheetForeColor" ="0"
dbLong "DatasheetForeColor12" ="0"
