SELECT tblMAINTENANCE_MONTHLY_CL.timeDate, tblMAINTENANCE_MONTHLY_CL.ultrasonicFilter, tblMAINTENANCE_MONTHLY_CL.plantNum, tblTECHNAME.firstName, tblTECHNAME.lastName
FROM tblTECHNAME RIGHT JOIN tblMAINTENANCE_MONTHLY_CL ON tblTECHNAME.ID = tblMAINTENANCE_MONTHLY_CL.techName
WHERE (((tblMAINTENANCE_MONTHLY_CL.timeDate)>=[TempVars]![tmpDate1] And (tblMAINTENANCE_MONTHLY_CL.timeDate)<=[TempVars]![tmpDate2]))
ORDER BY tblMAINTENANCE_MONTHLY_CL.timeDate;
