SELECT tblMAINTENANCE_WEEKLY_CL.timeDate, tblMAINTENANCE_WEEKLY_CL.safetyShower, tblMAINTENANCE_WEEKLY_CL.eyeFlush, tblMAINTENANCE_WEEKLY_CL.filterUS, tblTECHNAME.firstName, tblTECHNAME.lastName
FROM tblTECHNAME RIGHT JOIN tblMAINTENANCE_WEEKLY_CL ON tblTECHNAME.ID = tblMAINTENANCE_WEEKLY_CL.techName
WHERE (((tblMAINTENANCE_WEEKLY_CL.timeDate)>=[TempVars]![tmpDate1] And (tblMAINTENANCE_WEEKLY_CL.timeDate)<=[TempVars]![tmpDate2]))
ORDER BY tblMAINTENANCE_WEEKLY_CL.timeDate;
