SELECT tblPARTNUM.ID, tblPARTNUM.partNum, tblEP.ID, tblLEAK_CHECK.autoID, tblPRESS.ID
FROM ((tblPARTNUM LEFT JOIN tblEP ON tblPARTNUM.ID = tblEP.partNum) LEFT JOIN tblLEAK_CHECK ON tblPARTNUM.ID = tblLEAK_CHECK.partNum) LEFT JOIN tblPRESS ON tblPARTNUM.ID = tblPRESS.partNum;
