dbMemo "SQL" ="SELECT uSEAL.linker, uSEAL.seal, qryPARTNUM_ALL.partNumber\015\012FROM (select i"
    "d as linker, CSEAL1 as seal from tblEP_CSEAL union select id as linker, CSEAL2 f"
    "rom tblEP_CSEAL union select id as linker, CSEAL3 from tblEP_CSEAL)  AS uSEAL IN"
    "NER JOIN qryPARTNUM_ALL ON uSEAL.seal = qryPARTNUM_ALL.uniqID\015\012WHERE (((uS"
    "EAL.linker)=267))\015\012ORDER BY qryPARTNUM_ALL.partNumber;\015\012"
dbMemo "Connect" =""
dbBoolean "ReturnsRecords" ="-1"
dbInteger "ODBCTimeout" ="60"
dbByte "RecordsetType" ="0"
dbBoolean "OrderByOn" ="0"
dbByte "Orientation" ="0"
dbByte "DefaultView" ="2"
dbBoolean "FilterOnLoad" ="0"
dbBoolean "OrderByOnLoad" ="-1"
dbBoolean "TotalsRow" ="0"
