dbMemo "SQL" ="SELECT TOP 1 tblLEAK_CHECK.topNum, qryPARTNUM_ALL.partNumber AS topStr, tblLEAK_"
    "CHECK.bottomNum, qryPARTNUM_ALL_1.partNumber AS botStr, tblLEAK_CHECK.maniNum1, "
    "qryPARTNUM_ALL_2.partNumber AS manStr1, tblLEAK_CHECK.maniNum2, qryPARTNUM_ALL_3"
    ".partNumber AS manStr2, tblLEAK_CHECK.processLayout, tblLEAK_CHECK.filePage\015\012"
    "FROM ((((tblLEAK_CHECK LEFT JOIN refREV ON tblLEAK_CHECK.rev = refREV.ID) LEFT J"
    "OIN qryPARTNUM_ALL ON tblLEAK_CHECK.topNum = qryPARTNUM_ALL.uniqID) LEFT JOIN qr"
    "yPARTNUM_ALL AS qryPARTNUM_ALL_1 ON tblLEAK_CHECK.bottomNum = qryPARTNUM_ALL_1.u"
    "niqID) LEFT JOIN qryPARTNUM_ALL AS qryPARTNUM_ALL_2 ON tblLEAK_CHECK.maniNum1 = "
    "qryPARTNUM_ALL_2.uniqID) LEFT JOIN qryPARTNUM_ALL AS qryPARTNUM_ALL_3 ON tblLEAK"
    "_CHECK.maniNum2 = qryPARTNUM_ALL_3.uniqID\015\012WHERE (((tblLEAK_CHECK.partNum)"
    " = 276) And ((tblLEAK_CHECK.obsolete) = False) And ((tblLEAK_CHECK.[R&D]) = Fals"
    "e))\015\012ORDER BY refREV.rev DESC;\015\012"
dbMemo "Connect" =""
dbBoolean "ReturnsRecords" ="-1"
dbInteger "ODBCTimeout" ="60"
dbByte "RecordsetType" ="0"
dbBoolean "OrderByOn" ="0"
dbByte "Orientation" ="0"
dbByte "DefaultView" ="2"
dbBoolean "FilterOnLoad" ="0"
dbBoolean "OrderByOnLoad" ="-1"
dbBoolean "TotalsRow" ="0"
