SELECT tblPART_01.partNumber, tblPART_01_ELECTRODE.dia1, tblPART_01_ELECTRODE.len1, tblPART_01_ELECTRODE.dia2, tblPART_01_ELECTRODE.len2, tblPART_01_ELECTRODE.totLen, tblPART_01_ELECTRODE.specialFeatures, tblPART_01_ELECTRODE.groundElec, tblPART_01_ELECTRODE.multiGlandFix, tblPART_01_ELECTRODE.tapered, tblPART_01_ELECTRODE.stepped, tblPART_01.obsolete
FROM tblPART_01_ELECTRODE LEFT JOIN tblPART_01 ON tblPART_01_ELECTRODE.elecLink = tblPART_01.autoID
ORDER BY tblPART_01.partNumber;
