SELECT tblSPECIFICGRAVITY.timeDate, tblSPECIFICGRAVITY.timeHour, tblCHEMICALS.chemical, tblLINES.Line, tblSPECIFICGRAVITY.density, tblSPECIFICGRAVITY.measureTemp, tblSPECIFICGRAVITY.operTemp, tblTECHNAME.firstName, tblTECHNAME.lastName
FROM tblTECHNAME RIGHT JOIN (tblCHEMICALS RIGHT JOIN (tblLINES RIGHT JOIN tblSPECIFICGRAVITY ON tblLINES.ID = tblSPECIFICGRAVITY.line) ON tblCHEMICALS.ID = tblSPECIFICGRAVITY.chemical) ON tblTECHNAME.ID = tblSPECIFICGRAVITY.techName
WHERE (((tblSPECIFICGRAVITY.timeDate)>=[TempVars]![tmpDate1] And (tblSPECIFICGRAVITY.timeDate)<=[TempVars]![tmpDate2]))
ORDER BY tblSPECIFICGRAVITY.timeDate, tblCHEMICALS.chemical, tblLINES.Line;
