CREATE TABLE [tblMETALS_AAS] (
  [ID] AUTOINCREMENT CONSTRAINT [PrimaryKey] PRIMARY KEY UNIQUE NOT NULL,
  [timeDate] DATETIME ,
  [laboratory] LONG ,
  [acid] LONG ,
  [line] LONG ,
  [perAcid] DOUBLE ,
  [density] DOUBLE ,
  [Copper] DOUBLE ,
  [unitCu] LONG ,
  [Nickel] DOUBLE ,
  [unitNi] LONG ,
  [Iron] DOUBLE ,
  [unitFe] LONG ,
  [chromium] DOUBLE ,
  [unitCr] LONG ,
  [zinc] DOUBLE ,
  [unitZn] LONG ,
  [aluminum] DOUBLE ,
  [unitAl] LONG ,
  [molybdenum] DOUBLE ,
  [unitMo] LONG ,
  [comments] VARCHAR (255)
)
