CREATE TABLE [tblSURFACE_ANALYSIS_IC] (
  [ID] AUTOINCREMENT CONSTRAINT [PrimaryKey] PRIMARY KEY UNIQUE NOT NULL,
  [timeDate] DATETIME ,
  [laboratory] LONG ,
  [partNum] LONG ,
  [extrVol] DOUBLE ,
  [chloride] DOUBLE ,
  [bromide] DOUBLE ,
  [fluoride] DOUBLE ,
  [nitrate] DOUBLE ,
  [nitrite] DOUBLE ,
  [phosphate] DOUBLE ,
  [sulfate] DOUBLE ,
  [lithium] DOUBLE ,
  [sodium] DOUBLE ,
  [ammonium] DOUBLE ,
  [potassium] DOUBLE ,
  [magnesium] DOUBLE ,
  [calcium] DOUBLE ,
  [units] LONG ,
  [experiment] VARCHAR (255),
  [rnd] BIT ,
  [notes] VARCHAR (255)
)
