CREATE TABLE [tblSURFACE_ANALYSIS_AUGER] (
  [ID] AUTOINCREMENT CONSTRAINT [PrimaryKey] PRIMARY KEY UNIQUE NOT NULL,
  [timeDate] DATETIME ,
  [laboratory] LONG ,
  [rnd] BIT ,
  [modifications] VARCHAR (255),
  [Notes] LONGTEXT ,
  [testPart] LONG ,
  [carbon] DOUBLE ,
  [calcium] DOUBLE ,
  [chlorine] DOUBLE ,
  [chromium] DOUBLE ,
  [copper] DOUBLE ,
  [iron] DOUBLE ,
  [magnesium] DOUBLE ,
  [nickel] DOUBLE ,
  [nitrogen] DOUBLE ,
  [oxygen] DOUBLE ,
  [phosphorous] DOUBLE ,
  [potassium] DOUBLE ,
  [silicon] DOUBLE ,
  [sodium] DOUBLE ,
  [sulfur] DOUBLE ,
  [zinc] DOUBLE ,
  [oxideThick] DOUBLE ,
  [correctedThick] DOUBLE ,
  [crFeRatio] DOUBLE ,
  [maxCrFe] VARCHAR (50),
  [carbLayer] DOUBLE ,
  [ironLayer] DOUBLE 
)
