SELECT TOP 30 tblFUMEHOODS.timeDate, tblFUMEHOODS.timeHour, tblLINES.Line, tblCHEMICALS.chemical, tblFUMEHOODS.velocity, tblTECHNAME.firstName, tblTECHNAME.lastName
FROM tblCHEMICALS RIGHT JOIN (tblLINES RIGHT JOIN (tblTECHNAME RIGHT JOIN tblFUMEHOODS ON tblTECHNAME.ID = tblFUMEHOODS.techName) ON tblLINES.ID = tblFUMEHOODS.line) ON tblCHEMICALS.ID = tblFUMEHOODS.chemical
ORDER BY tblFUMEHOODS.timeDate DESC , tblFUMEHOODS.timeHour DESC;
