SELECT TOP 30 tblSPECIFICGRAVITY.timeDate, tblSPECIFICGRAVITY.timeHour, tblCHEMICALS.chemical, tblLINES.Line, tblSPECIFICGRAVITY.operTemp, tblSPECIFICGRAVITY.measureTemp, tblSPECIFICGRAVITY.density, tblTECHNAME.firstName, tblTECHNAME.lastName
FROM ((tblTECHNAME RIGHT JOIN tblSPECIFICGRAVITY ON tblTECHNAME.ID = tblSPECIFICGRAVITY.techName) LEFT JOIN tblCHEMICALS ON tblSPECIFICGRAVITY.chemical = tblCHEMICALS.ID) LEFT JOIN tblLINES ON tblSPECIFICGRAVITY.line = tblLINES.ID
ORDER BY tblSPECIFICGRAVITY.timeDate DESC , tblCHEMICALS.chemical, tblLINES.Line;
